---
- name: AWS IAM MCP Server Integration Demo
  hosts: aws_server
  gather_facts: false
  tasks:
    # Discover available AWS IAM tools
    - name: List all available AWS IAM tools
      ansible.mcp.mcp_get_tools:
      register: aws_tools

    - name: Display number of AWS IAM tools available
      ansible.builtin.debug:
        msg: "Found {{ aws_tools.tool_count }} AWS IAM tools available"

    # List existing IAM users
    - name: List existing IAM users
      ansible.mcp.mcp_run_tools:
        tool_name: list_users
        tool_args:
          ctx:
            content: []
            isError: false
          max_items: 100
      register: existing_users
      failed_when: false

    - name: Display existing users count
      ansible.builtin.debug:
        msg: "Found {{ existing_users.result.content.users | length }} existing IAM users"
      when: existing_users is succeeded and existing_users.result.content.users is defined

    - name: Display users list
      ansible.builtin.debug:
        msg: "User {{ item.user_name }} (ARN: {{ item.arn }}) - Created: {{ item.create_date }}"
      loop: "{{ existing_users.result.content.users }}"
      when: existing_users is succeeded and existing_users.result.content.users is defined

    - name: Handle list users error
      ansible.builtin.debug:
        msg: "Failed to list IAM users: {{ existing_users.result.content | default('Unknown error') }}"
      when: existing_users is failed or existing_users.result.is_error | default(false)
